export const LOG_ACTIONS = {
  POST: 'POST',
  PUT: 'PUT',
  DELETE: 'DELETE',
  GET: 'GET',
};

export const TASK_TYPE = {
  PROJECT_TASK: 'PROJECT_TASK',
  PROCEDURE_TASK: 'PROCEDURE_TASK',
  RECURRENT_TASK: 'RECURRENT_TASK',
};